# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.app:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '8080:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        ports:
            - '3306:3306'
        platform: linux/x86_64
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'boilerplate-a'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'sailmysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "password"]
          retries: 3
          timeout: 5s

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8090:80"
      links:
        - mysql
      environment:
        - PMA_HOST=mysql

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
